print('PALACSINTASÜTÉS')
n = int(input('Hány adag palacsintát akarsz sütni? '))
print('Ennyi hozzávaló kell: ')
print(f'Liszt: {20 * n} dkg')	
print(f'Tojás: {4 * n} db')
print(f'Só: {1 * n} csipet')	
print(f'Szénsavas ásványvíz: {5 * n} dl')
print(f'Tej: {7 * n} dl')	
print(f'Étolaj: {6 * n} ek')		
print(f'Liszt kilóban : {(20 * n) / 100} kg')
print(f'Ásványvíz literben: {5 * n / 10} l')
print(f'Tej literben {7 * n / 10} l')