print('Palacsintát sütsz.')
n = int(input('Hány palacsintát akarsz sütni? '))
print('Ennyi hozzávaló kell: ')
print(f'Liszt: {50 * n} dkg')	
print(f'Tojás: {4 * n} db')
print(f'Só: {1 * n} csipet')	
print(f'Szénsavas ásványvíz: {5 * n} dl')
print(f'Tej: {7 * n} dl')	
print(f'Étolaj: {6 * n} ek')		
